### ISSUE TITLE
null pointer when turn off plugin in main menu

### ISSUE THREAD

**Issue by Maurits825** [Maurits825/snake#2]
error:
```
[Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
        at com.snake.SnakePlugin.resetGame(SnakePlugin.java:172)
        at com.snake.SnakePlugin.lambda$shutDown$0(SnakePlugin.java:95)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:193)
        at client.ts(client.java:58003)
        at client.ah(client.java)
        at aw.a(aw.java:366)
        at aw.run(aw.java:345)
        at java.base/java.lang.Thread.run(Unknown Source)
```
`foodObject` is null
https://github.com/Maurits825/snake/blob/c5aa3e9b4218629b16bad045358a6d4579a9d35d/src/main/java/com/snake/SnakePlugin.java#L172

**Comment by Maurits825** [comment]
c5385fa
